skinparam {
	activityFontName "メイリオ"
	activityArrowFontName "メイリオ"
	circledCharacterFontName "メイリオ"
	classArrowFontName "メイリオ"
	classAttributeFontName "メイリオ"
	classFontName "メイリオ"
	classStereotypeFontName "メイリオ"
	componentFontName "メイリオ"
	componentStereotypeFontName "メイリオ"
	componentArrowFontName "メイリオ"
	noteFontName "メイリオ"
	packageFontName "メイリオ"
	sequenceActorFontName "メイリオ"
	sequenceDividerFontName "メイリオ"
	sequenceArrowFontName "メイリオ"
	sequenceGroupingFontName "メイリオ"
	sequenceGroupingHeaderFontName "メイリオ"
	sequenceParticipantFontName "メイリオ"
	sequenceTitleFontName "メイリオ"
	titleFontName "メイリオ"
	stateFontName "メイリオ"
	stateArrowFontName "メイリオ"
	stateAttributeFontName "メイリオ"
	usecaseFontName "メイリオ"
	usecaseStereotypeFontName "メイリオ"
	usecaseActorFontName "メイリオ"
	usecaseActorStereotypeFontName "メイリオ"
	usecaseArrowFontName "メイリオ"
	footerFontName "メイリオ"
	headerFontName "メイリオ"

	noteFontStyle bold
	noteFontColor #ffffff
	noteBackgroundColor #7f8c8d
	noteBorderColor #7f8c8d

	activityArrowColor #000000
	activityBackgroundColor #eeeeee
	activityBorderColor #999999
	activityStartColor #000000
	activityEndColor #000000
	activityBarColor #000000
	
	activityFontColor<<page>> #ffffff
	activityFontStyle<<page>> bold
	activityBorderColor<<page>> #2980b9
	activityBackgroundColor<<page>> #3498db

	activityFontColor<<error>> #ffffff
	activityFontStyle<<error>> bold
	activityBorderColor<<error>> #c0392b
	activityBackgroundColor<<error>> #e74c3c

	activityFontColor<<input>> #ffffff
	activityFontStyle<<input>> bold
	activityBorderColor<<input>> #16a085
	activityBackgroundColor<<input>> #1abc9c

	activityFontColor<<end>> #ffffff
	activityFontStyle<<end>> bold
	activityBorderColor<<end>> #2c3e50
	activityBackgroundColor<<end>> #34495e

	activityFontColor<<fail>> #ffffff
	activityFontStyle<<fail>> bold
	activityBorderColor<<fail>> #333333
	activityBackgroundColor<<fail>> #555555
	
	noteBackgroundColor<<q>> #f39c12
	noteBorderColor<<q>> #f39c12
}
